name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: test var
      run: |
        echo "GIT": ${GITHUB_HOST}
        echo "GET": ${secrets.USERNAME}
    - name: SSH test
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
