name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH test
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        PORT: ${{ secrets.PORT }}
