name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SSH test
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/poke-kit
          sudo git clone https://github.com/Magizchi/poke-kit.git
          sudo npm install
          sudo npm run build
          sudo npm run preview
